name: cruzroja
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  cloud_firestore: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  intl: 0.20.2
  json_annotation: ^4.8.1
  logger: ^2.0.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # hive_generator: ^2.0.1
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/ambulance.png
    - assets/descarga.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/descarga.png"
  