// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotHhBOdHUI1smuuwNWpE0B74bbanMCvc',
    appId: '1:120085245294:web:013526e3145333ae4aa57f',
    messagingSenderId: '120085245294',
    projectId: 'cruzroja-9015d',
    authDomain: 'cruzroja-9015d.firebaseapp.com',
    storageBucket: 'cruzroja-9015d.firebasestorage.app',
    measurementId: 'G-Z6D04XFK7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zW9OcONSgUKQko9Zt6_fdM0L3shwQGk',
    appId: '1:120085245294:android:25bb552135eff2154aa57f',
    messagingSenderId: '120085245294',
    projectId: 'cruzroja-9015d',
    storageBucket: 'cruzroja-9015d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6ZeGgSd4pwvyQ7jGSgH6fmnfdegiknI',
    appId: '1:120085245294:ios:48bad4465e9015924aa57f',
    messagingSenderId: '120085245294',
    projectId: 'cruzroja-9015d',
    storageBucket: 'cruzroja-9015d.firebasestorage.app',
    iosBundleId: 'com.example.cruzrojaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6ZeGgSd4pwvyQ7jGSgH6fmnfdegiknI',
    appId: '1:120085245294:ios:48bad4465e9015924aa57f',
    messagingSenderId: '120085245294',
    projectId: 'cruzroja-9015d',
    storageBucket: 'cruzroja-9015d.firebasestorage.app',
    iosBundleId: 'com.example.cruzrojaNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBotHhBOdHUI1smuuwNWpE0B74bbanMCvc',
    appId: '1:120085245294:web:59f45a48a1af178a4aa57f',
    messagingSenderId: '120085245294',
    projectId: 'cruzroja-9015d',
    authDomain: 'cruzroja-9015d.firebaseapp.com',
    storageBucket: 'cruzroja-9015d.firebasestorage.app',
    measurementId: 'G-BT8GKNQY75',
  );

}